site_name: My Notes
site_url: https://its-fonsy.github.io
theme:
  name: material

markdown_extensions:
  - footnotes
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.superfences:
      preserve_tabs: true
